UiConstants :: struct #type_info_none {
    HeightLine :: 22.0; // @todo Should depend on font size.
    PaddingHorizontal :: 50.0;
    PaddingHorizontalMedium :: 10.0;
    PaddingVertical :: 50.0;
    PaddingVerticalSmall :: 2.0;
    PaddingVerticalMedium :: 10.0;
    PaddingHorizontalSplit :: 20.0;
    PaddingHorizontalVariation :: 30.0;
    PaddingVerticalDecorumVariation :: 2.0;
    WidthDecorumVariation :: 4.0;
    PaddingCommentInline :: 5.0;
}
